CVE-2019-14900 fix
hmcts/cmc-claim-store pull request #2638
Opened 2022-09-22 22:02 UTC by tamir-b

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-09-27 08:13 UTC, sabahirfan commented
Build is failing, please fix that. Build it locally and get it passed there first.
`23:03:13  > Task :domain-model:compileJava FAILED
23:03:13  
23:03:13  FAILURE: Build failed with an exception.
23:03:13  
23:03:13  * What went wrong:
23:03:13  Execution failed for task ':domain-model:compileJava'.
23:03:13  > Could not resolve all files for configuration ':domain-model:compileClasspath'.
23:03:13     > Could not find org.hibernate:hibernate-validator:5.4.28.Final.
23:03:13       Required by:
23:03:13           project :domain-model > cz.jirutka.validator:validator-collection:2.2.0`

2022-09-27 16:03 UTC, asthamalviya approved these changes

2022-10-03 14:49 UTC, sabahirfan commented
Your build is still failing, please get this green.

2022-10-03 14:50 UTC, sabahirfan requested changes
Please fix the build

2022-10-04 15:56 UTC, asthamalviya approved these changes

2022-10-06 12:16 UTC, sabahirfan approved these changes

2022-10-06 12:52 UTC, merged