CIV-7830: Fix WebSecurityConfigurerAdapter Deprecated
hmcts/cmc-claim-store pull request #2735
Opened 2023-04-25 16:11 UTC by JackDevN

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-7830

### Change description ###

Fix the deprecation errors related to Spring security

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2023-04-26 14:25 UTC, hgulv1 approved these changes

2023-05-03 09:05 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/cmc/claimstore/config/SecurityConfiguration.java
>              "/v2/api-docs/**",
```suggestion
            "/v3/api-docs/**",
```

2023-05-03 09:13 UTC, sabahirfan commented
This one is still pending:
`cmc-claim-store/src/main/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverter.java:35: warning: [deprecation] containsClaim(String) in ClaimAccessor has been deprecated
        Boolean tokenName = jwt.containsClaim(TOKEN_NAME);
`

2023-05-03 09:14 UTC, sabahirfan requested changes
Please fix: 
```
cmc-claim-store/src/main/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverter.java:35: warning: [deprecation] containsClaim(String) in ClaimAccessor has been deprecated
        Boolean tokenName = jwt.containsClaim(TOKEN_NAME);

```

2023-05-05 14:23 UTC, sabahirfan approved these changes

2023-05-05 16:05 UTC, zikrurR approved these changes

2023-05-05 16:06 UTC, merged